### ISSUE TITLE
design 'Track Another' popup

### ISSUE THREAD

**Issue by sydneywalcoff** [sydneywalcoff/app-tracker#155]
### Overview
As a user, job hunting often comes in waves. This means, sometimes, I want to submit a new app to track and then immediate track a new one. Add a little popup asking if the user wants to track another.

### Action Items
- [ ] research UX examples
- [ ] design popup
- [ ] add design to #156 
- [ ] remove blocker from #156 and move to backlog

**Comment by sydneywalcoff** [comment]
Made unnecessary by #215

**Comment by sydneywalcoff** [comment]
Made unnecessary by #215
