### ISSUE TITLE
design new editAppStatus drop down

### ISSUE THREAD

**Issue by sydneywalcoff** [sydneywalcoff/app-tracker#86]
### Overview

As a User, the info most likely to be updated is the status/stage. I'd like there to be a way to update the status from the tracker table page.

### Action Items

- [x] drop down open
- [x] drop down closed
- [x] add design, remove blocker label, and move to backlog on #87
